// AUTO-GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
// Run `npm run optimize-images` to regenerate.

export type OptimizedImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = {
  "construction-hero": {
    "src": "/images/construction-hero.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAA8APu1iqU2ppaQiMAgBMB2JZwAAYcL+l0s4J9B+9YvAAPzXU0je9YhBe86QAdjtYQkZiJa4gdeuvwkEgepQEEkyqc4LIADqvOnOfcovz9FnepBWG+AA"
  },
  "construction-hero-alt": {
    "src": "/images/construction-hero-alt.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBdmUABlWmu/wXVQs63gbnAAAPyL/A3M5n8Ir/QY62ndCgYwasC8/SenTN4vwp5SZ4kueLMS3eeNbzBIhQaYl0B7Ho6ZM6PRhCeW0LfNzB9X5sz5iEG/SDgYV/oi3mjlIj2A85s4Dwg4xGAAAA=="
  },
  "gallery-hero": {
    "src": "/images/gallery-hero.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYgC1CIpJ/qUALPJiCNRBlw5oAP7k0p+/98nL0DQhbjyhSqAvFK6f3FFDQGpjTCkiUoTqsO6a/IDOo04Jv+h4UAKJn5GEMVliSLV8JBcvt4Tl7B950zUE0RzPhoqgC+bUN2NxIYgtAAAA"
  },
  "dumpster-hero": {
    "src": "/images/dumpster-hero.webp",
    "width": 1179,
    "height": 883,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAA8APu1iqU2ppaQiMAgBMB2JYwCdABu2NpvxltQ+jMBgAP6NMno0UE1vspq1OY+jViFdYQAuffedtNz2yDT0Wx+wVixh0yOYiR9jYOUpIKKTEL0hhrD+JNB3FL1kfN+6+6nWsQGVM2R/IAA="
  },
  "dumpster-1": {
    "src": "/images/dumpster-1.webp",
    "width": 1179,
    "height": 2092,
    "blurDataURL": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAABwBgCdASoUACQAPu1qqVAppiOiqqoBMB2JQBh1saLMXk/sCmr/Ddwn4NkBIXo6gArqdsp41D+7R41QiQAA/gUWBSQCv2MipUf1K0ZSNwe6T2JkRotnOrX82KLDs/tjo+LhupVTpVt5y41q22uGuMQPNEvLZnbKDIA+VdaD8S3mRxOXHcXxuWbv/h+Nhg3+8F0k989cSUHBO13DqAAYp3x5Mkbe3V+n+Ae+RZ6DY19PeMk72s5DDkq5TxOoxDTeNkYIbiqv2/G67sxai3FYkbbQ0uYyEpwNY+J9xsAAAAA="
  },
  "dumpster-2": {
    "src": "/images/dumpster-2.webp",
    "width": 1179,
    "height": 2093,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBQCdASoUACQAPu1epU2ppSMiMBqtUTAdiWMAyNQKcT7GNVujRLvMuh6NnEss45Df9IAA/q9uW/FIomQYgyjcV7/yDNixOYSVbI1mnqI6xVaNbwSq2+F8gWUgHyC1dDruaU1q9HQowazlwA/AjSknJDWuBtSy6StiSBYwBDmszj2TJgA32VRsVUMJN5C7KmIXAtvxGp+/CNxKNJLXAkIjglcZc9rlG3EJ9VIgAAA="
  },
  "project1": {
    "src": "/images/project1.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JYgC06B03EDY9xw1w0AD+5NK/s6tL2GjC3jR9rBAgW10cq+3OyWS05vHYx4VE5VB4PxW65ASQ7XZ0aip4ItjPxL9/I0P6/QCENQk2p7ZeXO9VAQTW30Tbzdax7/khfOKeRx8vA4RRs5eHEwAAAA=="
  },
  "project2": {
    "src": "/images/project2.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQAwCdASoUAA8APu1oqk6ppiQiMAgBMB2JQBgbglAG9pM7gzSwAPksLT7HQRHe6rLcaDGklHjiLR0Tm0C7TaQ9Rzvfu8loCDecjBPvYenHrXlIMIdJqii9Y2j0Z4ushMUCQAAA"
  },
  "project3": {
    "src": "/images/project3.webp",
    "width": 800,
    "height": 599,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JYwC7ABo5URnmUujm71m4AP4ZxJjmhda5z78EcKZ/2G22g6pwF255HdWmz38VbZFQHLRTPLcWMypkWp1Xwe7eiQn+ZD0pIwbbwa+Arrrf64wxAxnViz4vtAPRmGCIAAA="
  },
  "project4": {
    "src": "/images/project4.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYgC7ACHwqZy+NLkatCFYygAA/u8cwNvTOt/oV72JueZRssepuGYXDglsjrQ7lRJuUhis47d9iRPKFkc3Jpt92C92qT7GZFREUk1jC5Ev7JBdvEPEyy9j/ADPRvbctjYbdAAA"
  },
  "project5": {
    "src": "/images/project5.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZwDCgCGbNCE2/vA7fQJaAADN8Fns9gps0qK8YdPP49sJMuuxD1tqih6avGLd3UKlcKX/Qpv2mAppx87EO9zQSW0AeKFNDa+MfXx8zYl8nOoReidv+DGpkp2awAAA"
  },
  "project6": {
    "src": "/images/project6.webp",
    "width": 600,
    "height": 800,
    "blurDataURL": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAACQBQCdASoUABsAPu1sq1EppiOiqAqpMB2JZgCsABGjlBshttW/5PKzGQsabXyV7KnnPOf4uADNWvRMIr6Pz9eVYszqzygl5NYDrGLLxvOeSTnnd9fHh1aGL1DNccwBqnM36nITtGehBNjwv3UCZD8btCklUvAxFjmylQQZUCpL4vUhXucCSPRb+RQAunc1xpoznKi88uKzUnoJJiPGtSvLsvhbBtWshU294LZ3vEO7Mc0Zi6wiJ1f0p7ZLMyRMHiHPz+dQqUesRkll5GdobjcYAAA="
  },
  "project7": {
    "src": "/images/project7.webp",
    "width": 600,
    "height": 800,
    "blurDataURL": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAAAQBQCdASoUABsAPu1iq1AppSOisBgIATAdiWgAqPQLAZVaZHwDgv5Gbv5/mm9FIYkAANrePrLF7PfJAqvpo77padh6BaC0EpPdnFL8PNTE/XJunij/Hph08jXYPCVREifHNu7Q9eDDtlAOdoGOzTef9I22ckyVnZEPUbmaNbOuH3h8xvQxVtZJdpESyrqJtHVMBwyWGdimEdi7A+dh48Rcruce5Se6XmH0GkINROptPidL0npYo89eP7cNxJ/ljHDJACMbbHYxEaa7dlD0wMsa7LXBHWiR1o2KZgAA"
  },
  "project8": {
    "src": "/images/project8.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JZgC7AB4E/B5yKkAHTMAAAP48KboD8e7pQ9ObxRYoeGO01ZG1vXgDfSBXPHYCpnUJiH1EqPQhyp2uToZTb5OSu/NbjUPVu59GSavgdDUEa+yDilGXg4NLvAm/AAjvSbNLWBqkJgvkdMQAAAA="
  },
  "project9": {
    "src": "/images/project9.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JYgCdMoAApE/5OqaYAAD2IeTZQxRJX2lKjZMDLIpA9EB48zVe3BhEhMh9+CPHV2wbKxoVyRp8aZfAh3p0fX2688tKU344pODrQPVTBAeY0gDuDoTyj5orYs896rNuHgyLS3KQuSgAAA=="
  },
  "project10": {
    "src": "/images/project10.webp",
    "width": 800,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYwC7AYxim7I0V1mVbqHM+hpAvAD8M8GnRpfauRuTbFfe4Mz7uquwl6aLpzWuKklOdQfMxDlf6y6t0gOxY9i+nEEp4Wdo23vqWx2+C5uwobkFmzP25Bei9KaP4i40+oMKp59L8HYB3Eji5tucQaBHoHnPW3wR4AA="
  }
} as const satisfies Record<string, OptimizedImage>;

export type ImageKey = keyof typeof images;
