// One-time image optimization pipeline.
//
// Reads the curated source photos (large originals in public/deck_images and
// public/), resizes + compresses them to WebP in public/images/, and writes a
// typed manifest at src/lib/image-manifest.ts containing each image's final
// dimensions and a tiny base64 blur placeholder for next/image.
//
// Run with: npm run optimize-images

import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const outDir = path.join(root, "public", "images");
const manifestPath = path.join(root, "src", "lib", "image-manifest.ts");

const MAX_WIDTH = 2400;
const QUALITY = 78;

// key -> source file (relative to repo root). Keys become the manifest entries
// and the output filenames (public/images/<key>.webp).
const sources = {
  "hero-zoom-close": "public/images/hero-animation/hero-1.JPG",
  "hero-zoom-wide": "public/images/hero-animation/hero-2.JPG",
  "construction-hero": "public/deck_images/hero2.png",
  "construction-hero-alt": "public/deck_images/IMG_6267 2.jpeg",
  "gallery-hero": "public/deck_images/IMG_6234.jpeg",
  "dumpster-hero": "public/IMG_9800.jpg",
  "dumpster-1": "public/IMG_9801 2.jpg",
  "dumpster-2": "public/IMG_9802 2.jpg",
  project1: "public/deck_images/project1.jpeg",
  project2: "public/deck_images/project2.png",
  project3: "public/deck_images/project3.JPG",
  project4: "public/deck_images/project4.png",
  project5: "public/deck_images/project5.png",
  project6: "public/deck_images/project6.png",
  project7: "public/deck_images/project7.JPG",
  project8: "public/deck_images/project8.png",
  project9: "public/deck_images/project9.png",
  project10: "public/deck_images/project10.png",
};

// Load the previously generated manifest so we can preserve entries whose
// large source photos were removed (e.g. after a --clean run). Keys are
// double-quoted strings, so the object literal is valid JSON we can extract.
async function loadExistingManifest() {
  if (!existsSync(manifestPath)) return {};
  try {
    const text = await readFile(manifestPath, "utf8");
    const match = text.match(
      /export const images = (\{[\s\S]*?\}) as const satisfies/
    );
    if (!match) return {};
    return JSON.parse(match[1]);
  } catch (err) {
    console.warn(`WARN  could not parse existing manifest: ${err.message}`);
    return {};
  }
}

async function run() {
  await mkdir(outDir, { recursive: true });

  const existing = await loadExistingManifest();
  const manifest = {};
  let totalBefore = 0;
  let totalAfter = 0;

  for (const [key, relSource] of Object.entries(sources)) {
    const sourcePath = path.join(root, relSource);
    if (!existsSync(sourcePath)) {
      if (existing[key]) {
        manifest[key] = existing[key];
        console.log(`KEEP  ${key}: source missing, preserved existing entry`);
      } else {
        console.warn(`SKIP  ${key}: missing source ${relSource}`);
      }
      continue;
    }

    const input = await readFile(sourcePath);

    try {
      // Main optimized asset.
      const pipeline = sharp(input)
        .rotate() // respect EXIF orientation
        .resize({ width: MAX_WIDTH, withoutEnlargement: true })
        .webp({ quality: QUALITY });

      const { data, info } = await pipeline.toBuffer({ resolveWithObject: true });
      const outFile = path.join(outDir, `${key}.webp`);
      await writeFile(outFile, data);
      totalBefore += input.length;
      totalAfter += data.length;

      // Tiny blur placeholder (base64 WebP, ~20px wide).
      const blurBuf = await sharp(input)
        .rotate()
        .resize({ width: 20 })
        .webp({ quality: 40 })
        .toBuffer();
      const blurDataURL = `data:image/webp;base64,${blurBuf.toString("base64")}`;

      manifest[key] = {
        src: `/images/${key}.webp`,
        width: info.width,
        height: info.height,
        blurDataURL,
      };

      const kb = (n) => `${(n / 1024).toFixed(0)}KB`;
      console.log(
        `OK    ${key.padEnd(20)} ${kb(input.length).padStart(8)} -> ${kb(
          data.length
        ).padStart(7)}  (${info.width}x${info.height})`
      );
    } catch (err) {
      console.warn(`FAIL  ${key}: ${relSource} (${err.message.split("\n")[0]})`);
    }
  }

  const header = `// AUTO-GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
// Run \`npm run optimize-images\` to regenerate.

export type OptimizedImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, OptimizedImage>;

export type ImageKey = keyof typeof images;
`;

  await mkdir(path.dirname(manifestPath), { recursive: true });
  await writeFile(manifestPath, header);

  const mb = (n) => `${(n / 1024 / 1024).toFixed(1)}MB`;
  console.log(
    `\nDone. ${Object.keys(manifest).length} images. ${mb(totalBefore)} -> ${mb(
      totalAfter
    )}`
  );
}

// Optional: pass --clean to remove the large source directories after a
// successful run (public/deck_images and the stray dumpster originals).
async function clean() {
  const targets = [
    "public/deck_images",
    "public/IMG_9800.jpg",
    "public/IMG_9801 2.jpg",
    "public/IMG_9802 2.jpg",
  ];
  for (const t of targets) {
    const p = path.join(root, t);
    if (existsSync(p)) {
      await rm(p, { recursive: true, force: true });
      console.log(`removed ${t}`);
    }
  }
}

await run();
if (process.argv.includes("--clean")) {
  await clean();
}
